//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNetMDBTennis.UI {
    
    
    public partial class Billeder2015_Mesterskab {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ASPNetMDBTennis.SiteOrangeMaster Master {
            get {
                return ((ASPNetMDBTennis.SiteOrangeMaster)(base.Master));
            }
        }
    }
}
